# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
# We use preexec and precmd hook functions for Bash
# If you have anything that's using the Debug Trap or PROMPT_COMMAND 
# change it to use preexec or precmd
# See also https://github.com/rcaloras/bash-preexec

# Lot of settings taken from
# https://github.com/mrzool/bash-sensible/blob/master/sensible.bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


## GENERAL OPTIONS ##

# Enable history expansion with space
# E.g. typing !!<space> will replace the !! with your last command
bind Space:magic-space
# Kill whole line with Control-g
bind '"\C-g": kill-whole-line'
# Vi mode
# set -o vi

# set show-all-if-ambiguous on
# set completion-ignore-case on
# bind 'set show-all-if-ambiguous on'
# bind 'TAB:menu-complete'
# bind "set menu-complete-display-prefix on"

# Turn on recursive globbing (enables ** to recurse all directories)
shopt -s globstar 2> /dev/null

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;


## SANE HISTORY DEFAULTS ##

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Record each line as it gets issued
PROMPT_COMMAND='history -a'

# Huge history. Doesn't appear to slow things down, so why not?
HISTSIZE=500000
HISTFILESIZE=100000

# Avoid duplicate entries
HISTCONTROL="erasedups:ignoreboth"

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
HISTTIMEFORMAT='%F %T '


# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.  shopt -s checkwinsize 
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac


# Colors
color_reset='\[\033[0m\]'
sky_blue='\[\033[34m\]'
light_sky_blue='\[\033[1;34m\]'

blue='\[\033[36m\]'
light_blue='\[\033[1;36m\]'

red='\[\033[31m\]'
light_red='\[\033[1;31m\]'

green='\[\033[32m\]'
light_green='\[\033[1;32m\]'

purple='\[\033[35m\]'
light_purple='\[\033[1;35m\]'

white='\[\033[0m\]'

function prompt_command {
    # uncomment for a colored prompt, if the terminal has the capability; turned
    # off by default to not distract the user: the focus in a terminal window
    # should be on the output of commands, not on the prompt
    force_color_prompt=yes

    # Background processes
    BACKGROUND_JOBS_PROMPT=$( [ -z "$(jobs | tail -1)" ] && echo '' || echo " $green[\j]$color_reset")

    if [ -n "$force_color_prompt" ]; then
        if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
        else
        color_prompt=
        fi
    fi

    # Add git to prompt
    is_git() { 
        git status >/dev/null 2>&1 
    }

    GIT_PROMPT=''
    if is_git; then

        git_status=$(git status -sb)

        git_dirty_files=$(echo $git_status | grep '[AMD??]' -c) 
        git_dirty=''
        if [[ $git_dirty_files > 0 ]]; then
            git_dirty='\[\033[33m\]*'
        fi

        git_branch=" ($(git branch | sed -n 's/[*][a-zA-Z/]*//p' | cut -b 2- || ''))"

        git_ahead_amount=$(echo $git_status | grep 'ahead.[0-9]' -o | cut -b 7- )
        git_ahead=''
        if [[ $git_ahead_amount > 0 ]]; then
            # green
            git_ahead=" $green+$git_ahead_amount"
        fi

        git_behind=''
        git_behind_amount=$(echo $git_status | grep 'behind.[0-9]' -o | cut -b 8-)
        if [[ $git_behind_amount > 0 ]]; then
            # red 
            git_behind="$red-$git_behind_amount"
            
        fi

        GIT_PROMPT="$red$git_branch$git_dirty$git_ahead$git_behind$color_reset"
    fi

    if [ "$color_prompt" = yes ]; then
        PS1="$light_sky_blue\W$color_reset$GIT_PROMPT$BACKGROUND_JOBS_PROMPT "
    else
        PS1='\u@\h:\w'
    fi
}
PROMPT_COMMAND=prompt_command

# Get current branch (remove the whitespace from the begining)
# git_branch=$(git branch | sed -n 's/[*][a-zA-Z/]*//p' | cut -b 2- || '')
# echo $git_branch
# if [ "$color_prompt" = yes ]; then
#     PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $git_branch'
#     # PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
# else
#     PS1='\u@\h:\w '
#     # PS1='\u@\h:\w\$ '
# fi
unset color_prompt force_color_prompt

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# ignore case autocomlete
## SMARTER TAB-COMPLETION (Readline bindings) ##

# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"

# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"

# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"

# Immediately add a trailing slash when autocompleting symlinks to directories
bind "set mark-symlinked-directories on"


## BETTER DIRECTORY NAVIGATION ##

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null
# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
shell_dir=$HOME/.dotfiles/shell

. $shell_dir/env
. $shell_dir/aliases
. $shell_dir/functions

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# Source git completion
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
    . /usr/local/etc/bash_completion.d/git-completion.bash
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
# if ! shopt -oq posix; then
#   if [ -f /usr/share/bash-completion/bash_completion ]; then
#     . /usr/share/bash-completion/bash_completion
#   elif [ -f /etc/bash_completion ]; then
#     . /etc/bash_completion
#   fi
# fi

#disabling ctr-s behavior in terminal
stty -ixon


