#!/bin/bash

echo ""
echo "Do you want to bootstrap new system? (y/n)"

echo "Check the setup -folder if you wish to install only specific parts to your system"
echo ""
read

if [[ $REPLY = [yY] ]]; then 
    echo "Starting installation.."
    echo ""
else 
    echo "Aborting" 
    exit 1
fi


# setup folder
setup_dir=$HOME/.dotfiles/setup

# get os 
UNAME=$(uname)

# LINUX
if [[ "$UNAME" == 'Linux' ]]; then

    echo ""
    source $setup_dir/linux_pre_install
    echo ""
    source $setup_dir/symlink
    echo ""
    source $setup_dir/linux_programs
    echo ""
    source $setup_dir/setup_shell
    echo ""
    source $setup_dir/setup_fzf
    echo ""
    source $setup_dir/linux_post_install

# OSX
elif [[ "$UNAME" == 'Darwin' ]]; then

    echo ""
    source $setup_dir/osx_pre_install
    echo ""
    source $setup_dir/symlink
    echo ""
    source $setup_dir/osx_programs
    echo ""
    source $setup_dir/setup_shell
    echo ""
    source $setup_dir/setup_fzf
    echo ""
    source $setup_dir/osx_post_install

fi

echo ""
echo ""
echo "Dotfiles installed!"
