#!/bin/bash

# get this files directory (dotfiles directory)
dotfiles_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
setup_dir=$dotfiles_dir/setup

#source  helpers
. $dotfiles_dir/setup/helpers


install_all() {
    case "$(uname -sm)" in
        Darwin\ *)
            install_brew
            install_shell
            install_editor
            install_devenv
            install_desktop
            install_programs
            ;;
        Linux\ *64)
            install_shell
            install_editor
            install_devenv
            install_programs
            ;;
    esac
}

install_shell() {
    printf '===============================\n'
    printf 'SHELL\n\n' 

    $setup_dir/setup-shell
    $setup_dir/setup-fzf
    $setup_dir/setup-ripgrep
    $setup_dir/setup-tmux
    $setup_dir/setup-git

    printf '\nSHELL done!\n' 
    printf '===============================\n\n'
}

install_brew() {
    if [[ "$(uname)" == "Darwin" ]]; then

        printf '===============================\n'
        printf 'HOMEBREW\n\n' 

        $setup_dir/setup-brew

        printf '\nHOMEBREW installed!\n' 
        printf '===============================\n\n'
    else
        printf 'Brew setup only available in OSX!\n'
    fi
}

install_editor() {
    printf '===============================\n'
    printf 'EDITORS\n\n' 

    $setup_dir/setup-neovim
    $setup_dir/setup-vscode

    printf '\nEDITORS installed!\n' 
    printf '===============================\n\n'
}

install_devenv() {
    printf '===============================\n'
    printf 'DEVELOPMENT ENVIRONMENT\n\n' 

    $setup_dir/setup-node

    printf '\nDEVELOPMENT ENVIRONMENT setup done!\n'
    printf '===============================\n\n'
}

install_desktop() {
    printf '===============================\n'
    printf 'DESKTOP\n\n' 

    $setup_dir/setup-hammerspoon

    printf '\nDESKTOP done!\n' 
    printf '==============================\n\n'
}


install_programs() {
    printf '===============================\n'
    printf 'PROGRAMS\n\n' 

    printf '\nPROGRAMS installed!\n' 
    printf '===============================\n\n'
}

print_menu() {
    printf 'This script will help to bootstrap a new system.'
    printf '\n'
    printf 'Use the options below to install specific parts'
    printf '\n\n'

    printf 'Example usage: install --$arg ...'
    printf '\n\n'

    printf '%-15s  %-30s' ' --all' 'Setup whole environment' 
    printf '\n'

    printf '%-15s  %-30s' ' --brew (OSX)' 'Setup Homebrew for OSX' 
    printf '\n'

    printf '%-15s  %-30s' ' --shell' 'Setup basic shell environment (bashrc, rg, fzf, tmux, gitconfig)' 
    printf '\n'

    printf '%-15s  %-30s' ' --editor' 'Setup editors (neovim, vscode)' 
    printf '\n'

    printf '%-15s  %-30s' ' --devenv' 'Setup development environment (node)' 
    printf '\n'


    printf '%-15s  %-30s' ' --desktop' 'Setup specific desktop configuration (hammerspoon or ...)' 
    printf '\n'


    printf '%-15s  %-30s' ' --programs' 'Install additional programs' 
    printf '\n'

    printf '\n\n'
} 

# INIT
if [ -z "$1" ]; then
    print_menu
else
    for arg in "$@"; do
        case "$arg" in
            --all)
                install_all
                ;;
            --brew)
                install_brew
                ;;
            --shell)
                install_shell
                ;;
            --editor)
                install_editor
                ;;
            --devenv)
                install_devenv
                ;;
            --desktop) 
                install_desktop
                ;;
            --programs)
                install_programs
                ;;
        esac
    done
fi
