#!/bin/bash

# remove dock delay
defaults write com.apple.dock autohide-delay -float 0; killall Dock

# if you want to use default settings
# defaults delete com.apple.dock autohide-delay; killall Dock

# show library in finder
chflags nohidden ~/Library

# disable crash reporter
defaults write com.apple.CrashReporter DialogType none

