#!/bin/sh
# Add last modified date to the beginning of the file
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/BurntSushi/ripgrep/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

ripgrep_dir=$HOME/.dotfiles/roles/ripgrep/files/ripgrep-$LATEST_VERSION

old_versions=$HOME/.dotfiles/tools/ripgrep*

mkdir $ripgrep_dir
cd $ripgrep_dir

if [[ "$(uname)" == "Darwin" ]]; then
    TARGET_URL="https://github.com/BurntSushi/ripgrep/releases/download/$LATEST_VERSION/ripgrep-$LATEST_VERSION-x86_64-apple-darwin.tar.gz"
    TAR_PACKAGE=ripgrep-$LATEST_VERSION-x86_64-apple-darwin.tar.gz
    EXTRACTED_FOLDER=ripgrep-$LATEST_VERSION-x86_64-apple-darwin
else
    TARGET_URL="https://github.com/BurntSushi/ripgrep/releases/download/$LATEST_VERSION/ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl.tar.gz"
    TAR_PACKAGE=ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl.tar.gz
    EXTRACTED_FOLDER=ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl
fi

curl -OL $TARGET_URL
# tar -xvf $TAR_PACKAGE
# Extracting tar package, to -C 'direcotry' and stripping additional root folders
mkdir -p $ripgrep_dir/rg && tar -xvf $TAR_PACKAGE -C rg --strip-components=1

if [ ! -d $HOME/.local/bin ]; then
    mkdir -p $HOME/.local/bin
fi

# copy the new binary
cp $ripgrep_dir/rg/rg $HOME/.local/bin/rg


# remove the directory
rm -rf $ripgrep_dir
