#!/bin/bash

if [[ -d $HOME/.dotfiles/tools/fzf ]]; then
    echo "FZF repository already exists, updating"
    # Delete previous binaries
    cd $HOME/.dotfiles/tools/fzf/
    rm $HOME/.dotfiles/tools/fzf/bin/fzf
    rm $HOME/.dotfiles/tools/fzf/bin/fzf-tmux
    git pull
else
    echo "Cloning FZF repository..."
    git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.dotfiles/tools/fzf
fi

$HOME/.dotfiles/tools/fzf/install --bin

if [[ -e $HOME/.local/bin/fzf ]]; then
    rm $HOME/.local/bin/fzf
fi

ln -s $HOME/.dotfiles/tools/fzf/bin/fzf $HOME/.local/bin
