#!/bin/bash

#####################
# Dependencies

# requirements for Homebrew
printf "Installing xcode...\n"
xcode-select --install | echo "xcode-installed"


# Dont install if brew already exists
if ! exists brew; then
    printf "Installing homebrew...\n"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    printf "Homebrew already installed!\n"
fi

# Install required programs via Homebrew
taps=""
brews="zsh fzf ripgrep tmux neovim python3 node php composer mplayer htop tree"
casks="hammerspoon visual-studio-code firefox keeweb harvest rambox usb-overdrive windscribe slack"


for tap in $taps; do
    if brew tap | grep "$tap" > /dev/null; then
        printf "$tap already tapped! \n"
    else
        printf "Tapping $tap\n"
        brew tap $tap
    fi
done

for brew in $brews; do
    if brew list | grep "$brew" > /dev/null; then
        printf "$brew already installed \n"
    else
        printf "Installing $brew\n"
        brew install $brew
    fi
done

# Install ctags (they dont have official tap)
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

for cask in $casks; do
    if brew cask list | grep "$cask" > /dev/null; then
        printf "$cask already installed \n"
    else 
        printf "Installing $cask\n"
        brew cask install $cask
    fi
done

# Install neovim dependencies
if ! pip3 show neovim > /dev/null; then
    pip3 install neovim
    printf "Installing python neovim dependencies\n"
else
    printf "Python neovim dependencies already installed\n"
fi



#####################
# OTHER

#Install vim plugins automatically
bash -c "nvim  +PlugInstall +qall"

# Change default shell to zsh
if [[ $(echo $SHELL) =~ .*zsh.* ]]; then
    printf  "Changing default shell to zsh\n"
    sudo sh -c "echo $(which zsh) >> /etc/shells"
    chsh -s $(which zsh)
else
    printf "zsh already default shell\n"
fi
