#!/bin/bash

#####################
# Install programs
programs="zsh tmux neovim mplayer kitty php curl python3 python3-pip firefox ripgrep fzf"

sudo apt update

for program in $programs; do
     if ! exists $program; then
         printf "Installing $program\n"
         sudo apt install $program -y
     else
         printf "$program already installed\n"
     fi
done

# vscode
if ! exists code; then
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

    sudo apt-get update
    printf "Installing vscode \n"
    sudo apt-get install code -y # or code-insiders
else 
    printf "vscode already installed\n"
fi


#####################
# OTHER

#Install vim plugins automatically
bash -c "nvim  +PlugInstall +qall"

# Change default shell to zsh
chsh -s $(which zsh)

# Clean up unused programs
sudo apt autoremove
