#!/bin/bash

#####################
# Install programs
programs="zsh fzf ripgrep tmux neovim php composer curl python3 python3-pip node"

sudo dnf update

# Enable non-free repositories
sudo dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \

for program in $programs; do
     if ! exists $program; then
         printf "Installing $program\n"
         sudo dnf install $program -y
     else
         printf "$program already installed\n"
     fi
done

#####################
# Development dependencies

if ! pip3 list | grep neovim; then
    printf "Installing python neovim dependencies\n"
    pip3 install neovim
else
    printf "neovim python depencies already installed!\n"
fi


#####################
# OTHER

#Install vim plugins automatically
bash -c "nvim  +PlugInstall +qall"

# Change default shell to zsh
chsh -s $(which zsh)

# Clean up unused programs
sudo dnf autoremove
