#!/bin/bash

exists()
{
    command -v "$1" >/dev/null 2>&1
}

createLocalBinFolder() {
    local_user_bin=$HOME/.local/bin
    if [[ ! -d $local_user_bin ]]; then
        echo "$local_user_bin not found, creating directory"
        mkdir -p $local_user_bin
    fi
}
