#!/bin/bash

################################
# BIN 
################################
dotfiles_dir=$HOME/.dotfiles
target_bin=$HOME/.local/bin

echo "Checking if $target_bin exists..."
if [[ -d $target_bin ]]; then
    echo "$target_bin, exists!"
else
    echo "$target_bin not found, creating directory"
    mkdir -p $target_bin
fi

# Link files to target bin
echo "Linking files from $dotfiles_dir/bin to $target_bin"
for file_path in $dotfiles_dir/bin/*; do
    filename=$(basename $file_path)

    if [ -e $target_bin/$filename ]; then
        rm $target_bin/$filename
    fi

    # Make the actual link
    ln -s $file_path $target_bin
done
