#!/bin/bash

echo "Do you want to install programs specified in Brewfile? (y/n)"
read

if [[ $REPLY = [yY] ]]; then 
        cd $HOME/.dotfiles/
        echo "Installing programs..."
        brew tap Homebrew/bundle
        brew bundle
    else 
        echo "Skipping programs" 
    fi
