#!/bin/bash

exists()
{
  command -v "$1" >/dev/null 2>&1
}

if exists tmux; then
    echo "Tmux installed"
else
    echo "Installing tmux"
    if [[ "$(uname)" == 'Darwin' ]]; then
        brew install tmux
    else
        sudo apt install tmux -y
    fi
fi

echo "Linking tmux.conf to $HOME"
ln -sf $HOME/.dotfiles/tmux/tmux.conf $HOME/.tmux.conf

