#!/bin/bash

exists()
{
    command -v "$1" >/dev/null 2>&1
}

if exists code; then
    echo "vs-code already installed"
    exit 1
fi

echo "Installing vs-code"
if [[ "$(uname)" == 'Darwin' ]]; then
    if exists brew; then
        brew cask install visual-studio-code
    else
        echo "Homebrew is not installed. Run setup-brew."
    fi
else
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

    sudo apt-get update
    sudo apt-get install code -y # or code-insiders
fi

echo "Download 'syncing' extension and add your github gist id to download your settings"

