#!/bin/bash

if [[ -d $HOME/.dotfiles/tools/fzf ]]; then
    echo "FZF repository already exists, updating"
    # Delete previous binaries
    cd $HOME/.dotfiles/tools/fzf/
    rm $HOME/.dotfiles/tools/fzf/bin/fzf
    git pull
else
    echo "Cloning FZF repository..."
    git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.dotfiles/tools/fzf
fi

$HOME/.dotfiles/tools/fzf/install --bin

if [ ! -d $HOME/.local/bin ]; then
    mkdir -p $HOME/.local/bin
fi
	
ln -sf $HOME/.dotfiles/tools/fzf/bin/fzf $HOME/.local/bin/fzf
echo ""
