#!/bin/bash

# Setup programs and languages needed for development

exists()
{
    command -v "$1" >/dev/null 2>&1
}

case "$(uname -sm)" in
    Darwin\ *)
        if ! exists brew; then
            echo "Homebrew is not installed! Please run 'install --brew' to install it."
            exit 1
        fi

        brews="ctags composer php"
        casks="kitty virtualbox vagrant docker sequel-pro postman"

        for tap in $taps; do
            brew tap $tap
        done

        for brew in $brews; do
            brew install $brew
        done

        for cask in $casks; do
            brew cask install $cask
        done

        ;;
    Linux\ *64)
        programs="kitty kitty-terminfo virtualbox vagrant docker"

        for program in $programs; do
            sudo apt install $program -y
        done

        # nodejs
        curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        sudo apt-get install -y nodejs

        ;;
esac
