#!/bin/bash

exists()
{
  command -v "$1" >/dev/null 2>&1
}

# OSX
if [[ "$(uname)" == "Darwin" ]]; then
    # Make sure brew is installed
    if exists brew; then
        # install node
        brew install node
    else 
        echo "Brew was not found. Please run setup-brew."
    fi
else 
    # LINUX
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    sudo apt-get install -y nodejs
fi
