#!/bin/bash

exists()
{
    command -v "$1" >/dev/null 2>&1
}

# Link dotfiles
echo "Linking .bashrc, .bash_profile to $HOME"
ln -sf $HOME/.dotfiles/shell/bashrc $HOME/.bashrc
ln -sf $HOME/.dotfiles/shell/bash_profile $HOME/.bash_profile
ln -sf $HOME/.dotfiles/shell/dircolors $HOME/.dircolors

echo "Linking .zshrc to $HOME"
ln -sf $HOME/.dotfiles/shell/zshrc $HOME/.zshrc


# Install zsh
echo "Installing zsh.."

# Dont install if zsh already exists
if exists zsh; then
    echo "zsh already installed"
else
    if [[ "$(uname)" == 'Darwin' ]]; then
        # OSX
        if exists brew; then
            brew install zsh
        else
            echo "Homebrew is not installed. Run setup-brew."
        fi
    else
        # Linux
        sudo apt-get install zsh -y
    fi

fi

# Install oh-my-zsh, if it exists just do git pull
if [ -d $HOME/.config/oh-my-zsh ]; then
    echo "Updating oh-my-zsh..."
    cd $HOME/.config/oh-my-zsh 
    git pull
else 
    echo "Installing oh-my-zsh..."
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.config/oh-my-zsh
fi

# Change default shell to zsh
echo "Changing your default shell to zsh"
chsh -s $(which zsh)
