#!/bin/sh
# Add last modified date to the beginning of the file
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/BurntSushi/ripgrep/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

ripgrep_dir=$HOME/.dotfiles/tools/ripgrep-$LATEST_VERSION

old_versions=$HOME/.dotfiles/tools/ripgrep*

# Remove old versions
for version in $old_versions; do
    echo $(basename $version)
    if [ "$(basename $version)" != "ripgrep-$LATEST_VERSION" ]; then
        rm -rf $version
    fi
done

if [ -e $ripgrep_dir ]; then
    echo "Ripgrep already up to date"
    
else
    mkdir $ripgrep_dir
    cd $ripgrep_dir

    if [[ "$(uname)" == 'Darwin' ]]; then
        TARGET_URL="https://github.com/BurntSushi/ripgrep/releases/download/$LATEST_VERSION/ripgrep-$LATEST_VERSION-x86_64-apple-darwin.tar.gz"
        TAR_PACKAGE=ripgrep-$LATEST_VERSION-x86_64-apple-darwin.tar.gz
        EXTRACTED_FOLDER=ripgrep-$LATEST_VERSION-x86_64-apple-darwin
    else
        TARGET_URL="https://github.com/BurntSushi/ripgrep/releases/download/$LATEST_VERSION/ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl.tar.gz"
        TAR_PACKAGE=ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl.tar.gz
        EXTRACTED_FOLDER=ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl
    fi

    curl -OL $TARGET_URL
    tar -xvf $TAR_PACKAGE

    # Remove previous
    if [ -e $HOME/.local/bin/rg ]; then
        rm $HOME/.local/bin/rg
    fi
    # Link new binary
    ln -s $ripgrep_dir/$EXTRACTED_FOLDER/rg $HOME/.local/bin/rg

    # Remove tar file
    rm $TAR_PACKAGE
fi
