#!/bin/bash

old_dir=$HOME/dotfiles_old

echo "Linking .bashrc to $HOME"
ln -sf $HOME/.dotfiles/shell/bashrc $HOME/.bashrc
ln -sf $HOME/.dotfiles/shell/dircolors $HOME/.dircolors

echo "Linking .zshrc to $HOME"
ln -sf $HOME/.dotfiles/shell/zshrc $HOME/.zshrc


# Install oh-my-zsh, move previously installed version to dotfiles_old
if [ -d $HOME/.config/oh-my-zsh ]; then
    rm -rf $HOME/.config/oh-my-zsh
fi
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.config/oh-my-zsh
