#!/bin/bash

exists()
{
  command -v "$1" >/dev/null 2>&1
}


if [[ "$(uname)" == "Darwin" ]]; then
    # Make sure brew
    if exists brew; then
        echo "Installing hammerspoon"
        brew cask install 'hammerspoon'

        echo ""
        echo "Linking hammerspoon config..."
        if [ -d $HOME/.hammerspoon ] || [ -h $HOME/.hammerspoon ]; then
            rm -rf $HOME/.hammerspoon
        fi

        ln -s $HOME/.dotfiles/hammerspoon $HOME/.hammerspoon
        echo ""
    else
        echo "brew or brew cask command was not found, run setup-brew to install them!"
        echo ""
    fi
else
    echo "Hammerspoon available only in OSX!"
    echo ""
fi
    


