#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
    echo "Installing hammerspoon"
    brew cask install 'hammerspoon'

    echo ""
    echo "Linking hammerspoon config..."
    ln -sf $HOME/.dotfiles/hammerspoon $home/.hammerspoon
    echo ""
else
    echo "Hammerspoon available only in OSX!"
    echo ""
fi
    


